[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "aiogram>=3.18.0",
    "telegraph>=2.2.0",
    "yt-dlp>=2025.2.19",
]
